#
# Program to test serial port routines on different platforms.
#
# This is free and unencumbered software released into the public domain.
#
# (C) 2013, Ciellt AB, Stefan Petersen, (spe@ciellt.se)
#

CC=gcc
CFLAGS=-Wall
LDFLAGS=

sertest: sertest.o

clean:
	rm -f *~ *.o sertest
